name: ci-test-inson-travel-task

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

env:
    NODE_VERSION: 20.18.0
    # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    install:
        runs-on: ubuntu-latest
        if: ${{ !github.event.pull_request.draft }}
        steps:
            - name: Setup Node...
              uses: actions/checkout@v4
            - name: Use Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v4
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: npm install -g pnpm@9
            - name: Install dependencies...
              run: pnpm install --frozen-lockfile
              env:
                  CI: true

    lint:
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            - name: Install dependencies use cache...
              uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: npm install -g pnpm@9
            - name: Install dependencies...
              run: pnpm install --frozen-lockfile
            - name: Checking Linting...
              run: pnpm lint && pnpm format
              env:
                  CI: true
